export const BOOKING_TRANSITIONS = {
  PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['PROVIDER_ON_THE_WAY', 'CANCELLED', 'DISPUTED'],
  PROVIDER_ON_THE_WAY: ['IN_PROGRESS', 'CANCELLED', 'DISPUTED'],
  IN_PROGRESS: ['COMPLETED', 'DISPUTED'],
  COMPLETED: ['CUSTOMER_CONFIRMED', 'DISPUTED'],
  CUSTOMER_CONFIRMED: [],
  CANCELLED: [],
  DISPUTED: []
};

export const canTransitionBooking = (from, to) => (
  BOOKING_TRANSITIONS[from]?.includes(to) || false
);
